#pragma once

#include "src/common/config.h"

typedef enum {
    /* Keywords */
    TK_SELECT, TK_FROM, TK_WHERE, TK_INSERT, TK_INTO, TK_VALUES,
    TK_UPDATE, TK_SET, TK_DELETE, TK_CREATE, TK_TABLE, TK_DROP,
    TK_INDEX, TK_ON, TK_AND, TK_OR, TK_NOT, TK_NULL, TK_PRIMARY,
    TK_KEY, TK_UNIQUE, TK_INTEGER, TK_FLOAT, TK_VARCHAR, TK_BOOLEAN,
    TK_BEGIN, TK_COMMIT, TK_ROLLBACK, TK_TRANSACTION, TK_ISOLATION,
    TK_LEVEL, TK_READ, TK_COMMITTED, TK_UNCOMMITTED, TK_REPEATABLE,
    TK_EXPLAIN, TK_ORDER, TK_BY, TK_ASC, TK_DESC, TK_GROUP,
    TK_HAVING, TK_LIMIT, TK_JOIN, TK_INNER, TK_LEFT, TK_RIGHT,
    TK_AS, TK_COUNT, TK_SUM, TK_AVG, TK_MIN, TK_MAX,
    TK_BETWEEN, TK_IN, TK_IS, TK_LIKE, TK_TRUE, TK_FALSE,
    TK_IF, TK_EXISTS, TK_ALTER, TK_ADD, TK_COLUMN, TK_CONSTRAINT,
    TK_DEFAULT, TK_CHECK, TK_FOREIGN, TK_REFERENCES, TK_CASCADE,
    TK_OUTER, TK_CROSS, TK_FULL, TK_UNION, TK_ALL, TK_DISTINCT,
    TK_OFFSET, TK_ONLY, TK_SERIALIZABLE,

    /* Non-keywords */
    TK_IDENTIFIER, TK_INT_LITERAL, TK_FLOAT_LITERAL, TK_STRING_LITERAL,

    /* Operators */
    TK_EQUAL, TK_NOT_EQUAL, TK_LESS, TK_LESS_EQUAL, TK_GREATER,
    TK_GREATER_EQUAL, TK_PLUS, TK_MINUS, TK_STAR, TK_SLASH,

    /* Delimiters */
    TK_LEFT_PAREN, TK_RIGHT_PAREN, TK_COMMA, TK_SEMICOLON, TK_DOT,

    /* Special */
    TK_EOF, TK_ERROR,
} token_type_t;

typedef struct {
    token_type_t type;
    char    lexeme[256];
    int     line;
    int     column;
} token_t;

const char* token_type_to_string(token_type_t type);
