#include "token.h"

static const struct {
    token_type_t type;
    const char*  name;
} token_name_table[] = {
    { TK_SELECT,       "SELECT" },
    { TK_FROM,         "FROM" },
    { TK_WHERE,        "WHERE" },
    { TK_INSERT,       "INSERT" },
    { TK_INTO,         "INTO" },
    { TK_VALUES,       "VALUES" },
    { TK_UPDATE,       "UPDATE" },
    { TK_SET,          "SET" },
    { TK_DELETE,       "DELETE" },
    { TK_CREATE,       "CREATE" },
    { TK_TABLE,        "TABLE" },
    { TK_DROP,         "DROP" },
    { TK_INDEX,        "INDEX" },
    { TK_ON,           "ON" },
    { TK_AND,          "AND" },
    { TK_OR,           "OR" },
    { TK_NOT,          "NOT" },
    { TK_NULL,         "NULL" },
    { TK_PRIMARY,      "PRIMARY" },
    { TK_KEY,          "KEY" },
    { TK_UNIQUE,       "UNIQUE" },
    { TK_INTEGER,      "INTEGER" },
    { TK_FLOAT,        "FLOAT" },
    { TK_VARCHAR,      "VARCHAR" },
    { TK_BOOLEAN,      "BOOLEAN" },
    { TK_BEGIN,        "BEGIN" },
    { TK_COMMIT,       "COMMIT" },
    { TK_ROLLBACK,     "ROLLBACK" },
    { TK_TRANSACTION,  "TRANSACTION" },
    { TK_ISOLATION,    "ISOLATION" },
    { TK_LEVEL,        "LEVEL" },
    { TK_READ,         "READ" },
    { TK_COMMITTED,    "COMMITTED" },
    { TK_UNCOMMITTED,  "UNCOMMITTED" },
    { TK_REPEATABLE,   "REPEATABLE" },
    { TK_EXPLAIN,      "EXPLAIN" },
    { TK_ORDER,        "ORDER" },
    { TK_BY,           "BY" },
    { TK_ASC,          "ASC" },
    { TK_DESC,         "DESC" },
    { TK_GROUP,        "GROUP" },
    { TK_HAVING,       "HAVING" },
    { TK_LIMIT,        "LIMIT" },
    { TK_JOIN,         "JOIN" },
    { TK_INNER,        "INNER" },
    { TK_LEFT,         "LEFT" },
    { TK_RIGHT,        "RIGHT" },
    { TK_AS,           "AS" },
    { TK_COUNT,        "COUNT" },
    { TK_SUM,          "SUM" },
    { TK_AVG,          "AVG" },
    { TK_MIN,          "MIN" },
    { TK_MAX,          "MAX" },
    { TK_BETWEEN,      "BETWEEN" },
    { TK_IN,           "IN" },
    { TK_IS,           "IS" },
    { TK_LIKE,         "LIKE" },
    { TK_TRUE,         "TRUE" },
    { TK_FALSE,        "FALSE" },
    { TK_IF,           "IF" },
    { TK_EXISTS,       "EXISTS" },
    { TK_ALTER,        "ALTER" },
    { TK_ADD,          "ADD" },
    { TK_COLUMN,       "COLUMN" },
    { TK_CONSTRAINT,   "CONSTRAINT" },
    { TK_DEFAULT,      "DEFAULT" },
    { TK_CHECK,        "CHECK" },
    { TK_FOREIGN,      "FOREIGN" },
    { TK_REFERENCES,   "REFERENCES" },
    { TK_CASCADE,      "CASCADE" },
    { TK_OUTER,        "OUTER" },
    { TK_CROSS,        "CROSS" },
    { TK_FULL,         "FULL" },
    { TK_UNION,        "UNION" },
    { TK_ALL,          "ALL" },
    { TK_DISTINCT,     "DISTINCT" },
    { TK_OFFSET,       "OFFSET" },
    { TK_ONLY,         "ONLY" },
    { TK_SERIALIZABLE, "SERIALIZABLE" },
    { TK_IDENTIFIER,    "IDENTIFIER" },
    { TK_INT_LITERAL,   "INT_LITERAL" },
    { TK_FLOAT_LITERAL, "FLOAT_LITERAL" },
    { TK_STRING_LITERAL,"STRING_LITERAL" },
    { TK_EQUAL,         "=" },
    { TK_NOT_EQUAL,     "<>" },
    { TK_LESS,          "<" },
    { TK_LESS_EQUAL,    "<=" },
    { TK_GREATER,       ">" },
    { TK_GREATER_EQUAL, ">=" },
    { TK_PLUS,          "+" },
    { TK_MINUS,         "-" },
    { TK_STAR,          "*" },
    { TK_SLASH,         "/" },
    { TK_LEFT_PAREN,    "(" },
    { TK_RIGHT_PAREN,   ")" },
    { TK_COMMA,         "," },
    { TK_SEMICOLON,     ";" },
    { TK_DOT,           "." },
    { TK_EOF,           "EOF" },
    { TK_ERROR,         "ERROR" },
};

const char* token_type_to_string(token_type_t type) {
    for (int i = 0; i < (int)(sizeof(token_name_table) / sizeof(token_name_table[0])); i++) {
        if (token_name_table[i].type == type)
            return token_name_table[i].name;
    }
    return "UNKNOWN";
}
